[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
MakiePublication = "dde8697e-0d61-460d-88dd-856f66710dd1"
ModuleInfo = "3c3ff5e7-c68c-4a09-80d1-9526a1e9878a"
NonlinearContinua = "3a778109-d974-46c8-ac54-09f30d605bdf"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
Pollen = "c88717ad-5130-4874-a664-5a9aba5ec443"
SciMLExpectations = "afe9f18d-7609-4d0e-b7b7-af0cb72b8ea8"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"
