name = "Hyperelastics"
uuid = "c20c605d-adbe-46e4-9db6-e2b04c3ba023"
authors = ["Carson Farmer"]
version = "0.1.0"

[deps]
AbstractDifferentiation = "c29ec348-61ec-40c8-8164-b8c60e9d9f3d"
BibParser = "13533e5b-e1c2-4e57-8cef-cac5e52f6474"
Bibliography = "f1be7e48-bf82-45af-a471-ae754a193061"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Integrals = "de52edbc-65ea-441a-8357-d3a637375a31"
InverseLangevinApproximations = "b82787f2-62be-403e-9078-6d9feafd7ee3"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LossFunctions = "30fc2ffe-d236-52d8-8643-a9d8f7c094a7"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
Publish = "f065f642-d108-4f50-8aa5-6749150a895a"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"

[compat]
julia = "1.7"

[extras]
CPUSummary = "2a0fbf3d-bb9c-48f3-b0a9-814d99fd7ab9"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[publish]
ignore = ["^(gh-pages|juliamnt|julia.dmg)$"]
theme = "_Tracer-Theme"
title = "Hyperelastics.jl"

[targets]
test = ["Test"]
