name = "Hyperelastics"
uuid = "c20c605d-adbe-46e4-9db6-e2b04c3ba023"
authors = ["Carson Farmer"]
version = "0.1.0"

[deps]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
Integrals = "de52edbc-65ea-441a-8357-d3a637375a31"
InverseLangevinApproximations = "b82787f2-62be-403e-9078-6d9feafd7ee3"
LabelledArrays = "2ee39098-c373-598a-b85f-a56591580800"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NonlinearContinua = "3a778109-d974-46c8-ac54-09f30d605bdf"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SnoopPrecompile = "66db9d55-30c0-4569-8b51-7e840670fc0c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
Term = "22787eb5-b846-44ae-b979-8e399b8463ab"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"
LossFunctions = "30fc2ffe-d236-52d8-8643-a9d8f7c094a7"

[weakdeps]
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
MakieCore = "20f20a25-4f0e-4fdf-b5d1-57303727442b"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"

[extensions]
# HyperelasticsEnzyme = "Enzyme"
HyperelasticsFiniteDiff = "FiniteDiff"
HyperelasticsForwardDiff = "ForwardDiff"
HyperelasticsMakieCore = "MakieCore"
HyperelasticsPlots = "Plots"
HyperelasticsZygote = "Zygote"
HyperelasticsOptimization = "Optimization"

[compat]
julia = "1.9"

[extras]
CPUSummary = "2a0fbf3d-bb9c-48f3-b0a9-814d99fd7ab9"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[publish]
ignore = ["^(gh-pages|juliamnt|julia.dmg)$"]
theme = "_Tracer-Theme"
title = "Hyperelastics.jl"

[targets]
test = ["Test"]
